export default defineEventHandler(async (event) => {
  const { query, preferences } = await readBody(event)
  
  if (!query) {
    throw createError({ statusCode: 400, statusMessage: 'Query is required' })
  }

  try {
    // Get learning plan from the agent service
    const planResponse = await $fetch('http://localhost:8002/api/plans/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: {
        user_id: '550e8400-e29b-41d4-a716-446655440000',
        learning_goal: query,
        preferences: preferences || {
          experience_level: 'intermediate',
          time_commitment: '2 hours per day',
          learning_style: 'visual'
        }
      }
    })

    return {
      success: true,
      plan: planResponse
    }
  } catch (error) {
    console.error('Learning plan API error:', error)
    
    // Return mock plan if service is unavailable
    return {
      success: true,
      plan: {
        id: 'mock-plan-1',
        title: `Learning Plan: ${query}`,
        description: 'A personalized learning plan generated by AI',
        weeks: [
          {
            week: 1,
            title: 'Fundamentals',
            topics: ['Basic concepts', 'Setup and environment'],
            estimated_hours: 10
          },
          {
            week: 2,
            title: 'Core Concepts',
            topics: ['Key principles', 'Hands-on practice'],
            estimated_hours: 12
          },
          {
            week: 3,
            title: 'Advanced Topics',
            topics: ['Complex scenarios', 'Best practices'],
            estimated_hours: 15
          }
        ],
        total_duration_weeks: 3,
        estimated_total_hours: 37
      },
      fallback: true
    }
  }
})
